import initSmoothScroll from './modules/scroll-suave.js';
import animaScroll from './modules/scroll-animacao.js';
import initTabNav from './modules/init-tab-nav.js';
import initAccordion from './modules/init-accordion.js';
import initModal from './modules/modal.js';
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initFuncionamento from "./modules/funcionamento.js";
import initFetchAnimais from "./modules/fetch-animais.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";

initSmoothScroll();
animaScroll();
initTabNav();
initAccordion();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initFuncionamento();
await initFetchAnimais();
initFetchBitcoin();
